apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
        - name: studentapp
          image: nikstatus07/mystudentapp:latest
          ports:
            - containerPort: 8080