apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-studentapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-studentapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-studentapp
    spec:
      containers:
          - name: studentapp
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.containerPort }}